services:
  - type: web
    name: ega-website
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /img/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
